-- Infinite CRM — Warm Bucket persistent notes
--
-- The Warm Bucket page pulls contacts tagged "Positive" in PitchPrfct who
-- have gone quiet (last text from Nic sitting on delivered > 2h). Notes on
-- those contacts need to survive page reloads and cross-device sessions, so
-- we persist them here keyed by (user_id, pp_contact_uuid).
--
-- Contacts don't need a corresponding leads row — a warm-bucket note can
-- exist for someone who's only in PitchPrfct. When the agent promotes them
-- to the CRM, the lead is created and the note is copied over.
--
-- Safe to re-run.

CREATE TABLE IF NOT EXISTS public.warm_bucket_notes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  pp_contact_uuid TEXT NOT NULL,
  note            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, pp_contact_uuid)
);

CREATE INDEX IF NOT EXISTS warm_bucket_notes_user_idx
  ON public.warm_bucket_notes(user_id);

-- Keep updated_at fresh on every write
CREATE OR REPLACE FUNCTION public.warm_bucket_notes_touch()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS warm_bucket_notes_touch_tr ON public.warm_bucket_notes;
CREATE TRIGGER warm_bucket_notes_touch_tr
  BEFORE UPDATE ON public.warm_bucket_notes
  FOR EACH ROW EXECUTE FUNCTION public.warm_bucket_notes_touch();

-- ── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.warm_bucket_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "warm_bucket_notes_own_select" ON public.warm_bucket_notes;
CREATE POLICY "warm_bucket_notes_own_select" ON public.warm_bucket_notes FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "warm_bucket_notes_own_insert" ON public.warm_bucket_notes;
CREATE POLICY "warm_bucket_notes_own_insert" ON public.warm_bucket_notes FOR INSERT
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "warm_bucket_notes_own_update" ON public.warm_bucket_notes;
CREATE POLICY "warm_bucket_notes_own_update" ON public.warm_bucket_notes FOR UPDATE
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "warm_bucket_notes_own_delete" ON public.warm_bucket_notes;
CREATE POLICY "warm_bucket_notes_own_delete" ON public.warm_bucket_notes FOR DELETE
  USING (user_id = auth.uid());
