-- Infinite CRM — Per-user API keys for the public REST API
--
-- Each user can mint N keys from Settings. Kam (or any external automation)
-- sends the key in `X-API-Key` (or `Authorization: Bearer <key>`); the
-- Cloudflare Worker hashes it, looks up which user_id owns it, and scopes
-- every operation to that user. Deleted/revoked keys stop working instantly.
--
-- SECURITY MODEL:
--   * Plaintext keys are shown ONCE on creation and never stored — only the
--     SHA-256 hash lives in the DB. Even a full DB dump can't be used to
--     forge keys.
--   * key_hash is unique, so a hash collision (astronomically unlikely) or
--     duplicate insert fails cleanly.
--   * revoked_at != NULL disables the key without deleting the row (so we
--     keep an audit trail of "who had access when").
--   * RLS: users can only see/create/revoke their OWN keys. The worker uses
--     the service-role key to bypass RLS when validating an incoming request.
--
-- Safe to re-run.

CREATE TABLE IF NOT EXISTS public.api_keys (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  key_hash     TEXT NOT NULL UNIQUE,           -- SHA-256 hex of the plaintext key
  key_prefix   TEXT NOT NULL,                  -- first 8 chars of plaintext, shown in Settings for identification
  label        TEXT,                           -- human-friendly ("Kam", "n8n prod", etc.)
  scopes       TEXT[] NOT NULL DEFAULT ARRAY[
                 'leads:read','leads:write','tags:read','tags:write',
                 'stages:read','activity:write'
               ]::TEXT[],
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,                    -- worker updates on each successful auth
  revoked_at   TIMESTAMPTZ                     -- non-null means the key is dead
);

CREATE INDEX IF NOT EXISTS api_keys_user_id_idx  ON public.api_keys(user_id);
CREATE INDEX IF NOT EXISTS api_keys_key_hash_idx ON public.api_keys(key_hash) WHERE revoked_at IS NULL;

-- ── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "api_keys_own_select" ON public.api_keys;
CREATE POLICY "api_keys_own_select" ON public.api_keys FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "api_keys_own_insert" ON public.api_keys;
CREATE POLICY "api_keys_own_insert" ON public.api_keys FOR INSERT
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "api_keys_own_update" ON public.api_keys;
CREATE POLICY "api_keys_own_update" ON public.api_keys FOR UPDATE
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "api_keys_own_delete" ON public.api_keys;
CREATE POLICY "api_keys_own_delete" ON public.api_keys FOR DELETE
  USING (user_id = auth.uid());
