-- Infinite CRM — Warm Bucket manual queue
--
-- Lets external automations (Kam via the Infinite public API, future manual
-- add-to-bucket UI, etc.) push high-priority contacts INTO Nic's warm bucket
-- alongside the PitchPrfct auto-scan. Kam's AI decides "this one needs to
-- be called" and POSTs it here; it shows up in the Warm Bucket page right
-- next to the PP-scanned positives.
--
-- Rows stay pending until Nic marks them contacted or dismissed. Dismissal
-- is soft-delete via `status='dismissed'` so we keep an audit trail of what
-- Kam suggested vs what Nic acted on.
--
-- Safe to re-run.

CREATE TABLE IF NOT EXISTS public.warm_bucket_queue (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  phone        TEXT NOT NULL,
  first_name   TEXT,
  last_name    TEXT,
  email        TEXT,
  state        TEXT,
  zip          TEXT,
  note         TEXT,
  reason       TEXT,          -- why Kam pushed this: "asked about family plan", etc.
  priority     INT DEFAULT 3, -- 1 (low) to 5 (urgent). Sort key for the queue.
  source       TEXT DEFAULT 'api',   -- 'api' | 'manual' | 'system'
  external_id  TEXT,          -- Kam's own ID for idempotency on retries
  status       TEXT DEFAULT 'pending', -- 'pending' | 'contacted' | 'dismissed'
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, phone)  -- one queue entry per phone per user; API upserts
);

CREATE INDEX IF NOT EXISTS warm_bucket_queue_user_status_idx
  ON public.warm_bucket_queue(user_id, status);

CREATE OR REPLACE FUNCTION public.warm_bucket_queue_touch()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS warm_bucket_queue_touch_tr ON public.warm_bucket_queue;
CREATE TRIGGER warm_bucket_queue_touch_tr
  BEFORE UPDATE ON public.warm_bucket_queue
  FOR EACH ROW EXECUTE FUNCTION public.warm_bucket_queue_touch();

-- ── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.warm_bucket_queue ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "warm_bucket_queue_own_select" ON public.warm_bucket_queue;
CREATE POLICY "warm_bucket_queue_own_select" ON public.warm_bucket_queue FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "warm_bucket_queue_own_insert" ON public.warm_bucket_queue;
CREATE POLICY "warm_bucket_queue_own_insert" ON public.warm_bucket_queue FOR INSERT
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "warm_bucket_queue_own_update" ON public.warm_bucket_queue;
CREATE POLICY "warm_bucket_queue_own_update" ON public.warm_bucket_queue FOR UPDATE
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "warm_bucket_queue_own_delete" ON public.warm_bucket_queue;
CREATE POLICY "warm_bucket_queue_own_delete" ON public.warm_bucket_queue FOR DELETE
  USING (user_id = auth.uid());
