-- Infinite CRM — PitchPrfct per-agent automation
-- Run this ONCE in the Supabase dashboard -> SQL editor. Safe to re-run.

-- 1) Workflow routing rules — keyword(comment) -> workflow map + delay, per
--    agent. Not sensitive. Lives on the profile row as JSONB.
alter table public.profiles
  add column if not exists pitchprfct_rules jsonb;

-- 2) Per-agent PitchPrfct API key. SEPARATE table with row-level security so
--    each agent can only ever read/write their OWN key. The email Worker reads
--    keys with the service role, which bypasses RLS.
create table if not exists public.pitchprfct_keys (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  api_key    text,
  updated_at timestamptz not null default now()
);

alter table public.pitchprfct_keys enable row level security;

drop policy if exists "pitchprfct_keys own select" on public.pitchprfct_keys;
drop policy if exists "pitchprfct_keys own insert" on public.pitchprfct_keys;
drop policy if exists "pitchprfct_keys own update" on public.pitchprfct_keys;

create policy "pitchprfct_keys own select" on public.pitchprfct_keys
  for select using (auth.uid() = user_id);
create policy "pitchprfct_keys own insert" on public.pitchprfct_keys
  for insert with check (auth.uid() = user_id);
create policy "pitchprfct_keys own update" on public.pitchprfct_keys
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 3) Delay queue — when an agent sets a delay, a new lead is parked here
--    instead of enrolled immediately. The Worker's cron trigger enrolls rows
--    once enroll_at passes; the agent can flip a row to 'cancelled' first.
--    Worker (service role) inserts + processes; agents read/cancel their own.
create table if not exists public.pitchprfct_queue (
  id         bigint generated by default as identity primary key,
  lead_id    uuid not null,
  user_id    uuid not null references auth.users(id) on delete cascade,
  enroll_at  timestamptz not null,
  status     text not null default 'pending',  -- pending|done|cancelled|failed
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pitchprfct_queue_due_idx
  on public.pitchprfct_queue (status, enroll_at);
create index if not exists pitchprfct_queue_lead_idx
  on public.pitchprfct_queue (lead_id);

alter table public.pitchprfct_queue enable row level security;

drop policy if exists "pitchprfct_queue own select" on public.pitchprfct_queue;
drop policy if exists "pitchprfct_queue own update" on public.pitchprfct_queue;

create policy "pitchprfct_queue own select" on public.pitchprfct_queue
  for select using (auth.uid() = user_id);
create policy "pitchprfct_queue own update" on public.pitchprfct_queue
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
